#!/bin/bash

echo "🔧 Configuración de Variables de Entorno para Render"
echo "=================================================="
echo ""

echo "📋 Variables que necesitas configurar en Render:"
echo ""
echo "1. POSTGRES_URI o DATABASE_URL:"
echo "   - Ve a tu dashboard de Render"
echo "   - Selecciona tu servicio de API"
echo "   - Ve a 'Environment'"
echo "   - Agrega: POSTGRES_URI"
echo "   - Valor: La URL de tu base de datos PostgreSQL"
echo ""
echo "2. JWT_SECRET:"
echo "   - Agrega: JWT_SECRET"
echo "   - Valor: Una cadena secreta aleatoria (ej: 'mi-secreto-super-seguro-2025')"
echo ""
echo "3. NODE_ENV:"
echo "   - Agrega: NODE_ENV"
echo "   - Valor: production"
echo ""
echo "4. CLIENT_URL (opcional):"
echo "   - Agrega: CLIENT_URL"
echo "   - Valor: https://tu-cliente.onrender.com"
echo ""

echo "🔍 Para obtener la URL de la base de datos:"
echo "1. Ve a tu dashboard de Render"
echo "2. Selecciona tu servicio de base de datos PostgreSQL"
echo "3. Ve a 'Connections'"
echo "4. Copia la 'External Database URL'"
echo ""

echo "⚠️  IMPORTANTE:"
echo "- Después de configurar las variables, Render reiniciará automáticamente tu servicio"
echo "- Esto puede tomar 2-3 minutos"
echo ""

echo "🧪 Para verificar la configuración:"
echo "curl https://betcontrol-y3y6.onrender.com/api/init/diagnose"
echo ""

echo "🚀 Para inicializar la base de datos después de configurar:"
echo "curl -X POST https://betcontrol-y3y6.onrender.com/api/init/init-database"
echo ""
