#!/bin/bash

echo "🗄️  Configuración de Base de Datos PostgreSQL en Render"
echo "====================================================="
echo ""

echo "📋 Pasos para crear una base de datos PostgreSQL:"
echo ""
echo "1. Ve a https://dashboard.render.com/"
echo "2. Haz clic en 'New +'"
echo "3. Selecciona 'PostgreSQL'"
echo "4. Configura:"
echo "   - Name: betcontrol-db"
echo "   - Database: betcontrol"
echo "   - User: betcontrol_user"
echo "   - Region: El más cercano a ti"
echo "   - PostgreSQL Version: 15 (o la más reciente)"
echo "5. Haz clic en 'Create Database'"
echo ""

echo "🔍 Después de crear la base de datos:"
echo "1. Ve a tu nuevo servicio de PostgreSQL"
echo "2. Busca la sección 'Connections' o 'Info'"
echo "3. Copia la 'External Database URL'"
echo "   (Se ve así: postgresql://user:password@host:port/database)"
echo ""

echo "⚙️  Configurar variables de entorno:"
echo "1. Ve a tu servicio de API (betcontrol-y3y6)"
echo "2. Pestaña 'Environment'"
echo "3. Agrega estas variables:"
echo ""
echo "   POSTGRES_URI = [URL que copiaste de la base de datos]"
echo "   JWT_SECRET = mi-secreto-super-seguro-2025"
echo "   NODE_ENV = production"
echo ""

echo "🧪 Para verificar después de configurar:"
echo "curl https://betcontrol-y3y6.onrender.com/api/init/diagnose"
echo ""

echo "🚀 Para inicializar la base de datos:"
echo "curl -X POST https://betcontrol-y3y6.onrender.com/api/init/init-database"
echo ""

echo "💡 Alternativa: Si no encuentras 'Connections', busca:"
echo "- 'Info' tab"
echo "- 'Settings' tab"
echo "- 'Overview' tab"
echo "- Cualquier sección que muestre información de conexión"
echo ""
